### ISSUE TITLE
>=Cyphertite-1.6.7 requires >=assl-1.5.0

### ISSUE THREAD

**Issue by pstn** [conformal/cyphertite#71]
Cyphertite now requires a higher version of assl to compile for me than it is specified in cyphertite/config/cyphertite.spec:21. I need assl-1.5.0 instead of assl-1.4.1 to build cyphertite-1.6.7 and cphertite-2.0.0. When I build with assl-1.4.1 the compiler fails with

ct_util.c: In function 'ct_ssl_connect':
ct_util.c:530:28: error: storage size of 'aco' isn't known

**Comment by pstn** [comment]
Discontinued project
